### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by shahoob**
# Why I am doing this

1. Waiting lines? nope
2. Part of the GitHub ecosystem

### CODE REVIEW

**Comment by shahoob** [comment]
now it finally works, just need to start both server without the &s.
if you need to know why then read [this](https://github.com/cypress-io/github-action#start-multiple-servers)

**Comment by shahoob** [comment]
What do you think @mfrachet?
Migrating to GitHub Actions might be better.

**Comment by mfrachet** [comment]
Let's try this one, thank you for your help and contributions 👍🏻

**Comment by shahoob** [comment]
> Let's try this one, thank you for your help and contributions 👍🏻

You're welcome 😉

**Pull request merged**
